### ISSUE TITLE
Create the Blog Post content type

### ISSUE THREAD

**Issue by edysmp** [edysmp/stand-blog#2]
Mockup URL: https://templatemo.com/templates/templatemo_551_stand_blog/post-details.html

Create the the `Blog post` content type.
```
Name: Blog post
Machine name: blog
```

Possible fields:

Image:
Field type: Media. Use the Media type: File // Needs to install Media and Media Library(both are part of the core). Create a Image media type - if not exists.

Body -> text. Usually comes by default for new Content types.

Tags:
Field type: Taxonomy term. // Use the Tags taxonomy as the taxonomy.

**Comment by Luis93Hub** [comment]
it was Create the the Blog post content type

Installed> Media, Media library
add Content types media and Taxonomy Term
