### ISSUE TITLE
Remove default the "Basic block" Block Type

### ISSUE THREAD

**Issue by edysmp** [edysmp/stand-blog#27]
## Description
We are creating another custom block types and we will not use thise default block type.

## Test Instructions

What: 
When: 
Where: 
How:

**Comment by edysmp** [comment]
@Luis93Hub is this done?

**Comment by Luis93Hub** [comment]
Yes it was done.

![image](https://user-images.githubusercontent.com/102109226/180625332-0d9a7455-e3cd-4aab-801b-128a4c6a1109.png)
